<?php
namespace app\demo\action;

use app\demo\service\UserService;
use herosphp\core\Controller;
use herosphp\core\Loader;
use herosphp\http\HttpRequest;
use herosphp\model\CommonService;
use herosphp\utils\FileUpload;

/**
 * demo action
 * @package commom\action
 * @author yangjian<yangjian102621@gmail.com>
 */
class DbAction extends Controller {

    /**
     * @var CommonService
     */
    protected $service;

    public function C_start()
    {
        parent::C_start(); // TODO: Change the autogenerated stub
        $this->service = Loader::service(UserService::class);
    }

    /**
     * 首页
     * @param HttpRequest $request
     */
    public function index(HttpRequest $request) {

        $item = $this->service->alias('a')
            ->fields('a.id, a.username, a.password, b.create_by, create_date, b.number')
            ->join('content b', MYSQL_JOIN_RIGHT)
            ->on('a.id = b.id')
            ->count();
        __print($item);
        $items = $this->service->alias('a')
            ->fields('a.id, a.username, a.password, b.create_by, create_date, b.number')
            ->join('content b', MYSQL_JOIN_RIGHT)
            ->on('a.id = b.id')
            ->find();
        __print($items);
        die();
    }

    /**
     * 添加数据
     * @param HttpRequest $request
     */
    public function add(HttpRequest $request) {
        $data = [
            'username' => 'xiaoming',
            'password' => '233dsadsad',
            'add_time' => date('Y-m-d H:i:s')
        ];
        echo $this->service->add($data);
        die();
    }

    public function delete(HttpRequest $request) {
        $this->service->delete(18);
        $this->service->where('id', '>', 19)->deletes();
        __print($this->service->find());
        die();
    }

    public function update(HttpRequest $request) {
        $this->service->beginTransaction();
        $this->service->where('id', 19)->updates(['username' => 'xiaoming']);
        __print($this->service->findById(19));
        $this->service->rollback();
        __print($this->service->findById(19));
        die();
    }

}
