#!/usr/bin/env php
<?php
/**
 * * ---------------------------------------------------------------------
 * artisan入口程序
 * @author yangjian102621@gmail.com
 * ---------------------------------------------------------------------
 * Copyright (c) 2013-now http://www.r9it.com All rights reserved.
 * Licensed ( http://www.apache.org/licenses/LICENSE-2.0 )
 * ---------------------------------------------------------------------
 */
require_once __DIR__."/server.php";
\herosphp\BootStrap::artisan();

