<?php
/**
 * 单元测试类
 * @author yangjian<yangjian102621@gmail.com>
 * @date 2017-06-20
 */

namespace app\demo\tests;
use app\demo\service\DemoService;
use app\demo\service\UserService;
use herosphp\core\Loader;
use app\demo\dao\UserDao;
use herosphp\http\HttpClient;

class DemoServiceTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var DemoService
     */
    protected $service;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->service = new DemoService();
    }

    /**
     * @test
     */
    public function sqlBuilder() {

        $model = Loader::model(UserDao::class);
        $model->where("name", "aaaa")->where("age", ">", 100)
            ->where(function($model) use ($model) {
                $model->where("id", 10)->whereOr('name', "xiaoming");
            })
            ->whereOr(function($model) use ($model) {
                $model->where("ischeck", 0)->where("addtime", ">", "2017-06-20 13:30:30")->whereOr('ddd', 'xxx');
            });
        print_r($model->getSqlBuilder()->buildQueryString());
    }

    /**
     * @test
     */
    public function hello() {
        $this->assertTrue($this->service->hello());
    }

    /**
     * @test
     */
    public function findOne() {
        $model = Loader::service(UserService::class);
        print_r($model->findOne());
    }
}
