<?php
/**
 * 单元测试类
 * @author yangjian<yangjian102621@gmail.com>
 * @date 2017-06-20
 */

namespace app\demo\tests;
use app\admin\service\AdminService;
use herosphp\core\Loader;

class DemoTest extends \PHPUnit_Framework_TestCase
{

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    /**
     * @test
     */
    public function sqlBuilder() {

        $model = Loader::model(UserDao::class);
        $model->where("name", "aaaa")->where("age", ">", 100)
            ->where(function($model) use ($model) {
                $model->where("id", 10)->whereOr('name', "xiaoming");
            })
            ->whereOr(function($model) use ($model) {
                $model->where("ischeck", 0)->where("addtime", ">", "2017-06-20 13:30:30")->whereOr('ddd', 'xxx');
            });
        print_r($model->getSqlBuilder()->buildQueryString());
    }

    /**
     * @test
     */
    public function findOne() {
        $model = Loader::service(AdminService::class);
        print_r($model->findOne());
    }

    /**
     * 查找某个字段是否包含某个字符串
     * @test
     */
    public function contain() {
        $model = Loader::service(AdminService::class);
        $users = $model->fields('id, username')->where('username', 'CONTAIN', 'admin')->find();
        var_dump($users);
    }
}
